module.exports = async (localSourcePath) => {
  const presets = {
    highQuality: [
      '-c:v libx264',
      '-preset fast',
      '-profile:v high',
      '-crf 22',
      '-coder 1',
      '-c:a aac',
      '-ac 2',
      '-b:a 320K',
      '-ar 48000',
      '-profile:a aac_low',
    ],
    '2160p': [
      '-c:v libx264',
      '-preset fast',
      '-profile:v high',
      '-vf scale=3840:-2',
      '-crf 26',
      '-coder 1',
      '-pix_fmt yuv420p',
      '-bf 2',
      '-c:a aac',
      '-ac 2',
      '-b:a 192K',
      '-ar 48000',
      '-profile:a aac_low',
    ],
    '1440p': [
      '-c:v libx264',
      '-preset fast',
      '-profile:v high',
      '-vf scale=2560:-2',
      '-crf 26',
      '-coder 1',
      '-pix_fmt yuv420p',
      '-bf 2',
      '-c:a aac',
      '-ac 2',
      '-b:a 192K',
      '-ar 48000',
      '-profile:a aac_low',
    ],
    '1080p': [
      '-c:v libx264',
      '-preset fast',
      '-profile:v high',
      '-vf scale=1920:-2',
      '-crf 26',
      '-coder 1',
      '-pix_fmt yuv420p',
      '-bf 2',
      '-c:a aac',
      '-ac 2',
      '-b:a 192K',
      '-ar 48000',
      '-profile:a aac_low',
    ],
    '720p': [
      '-c:v libx264',
      '-preset fast',
      '-profile:v high',
      '-vf scale=1280:-2',
      '-crf 27',
      '-coder 1',
      '-pix_fmt yuv420p',
      '-bf 2',
      '-c:a aac',
      '-ac 2',
      '-b:a 128K',
      '-ar 48000',
      '-profile:a aac_low',
    ],
  };

  // query the video with ffprobe
  // decide what presets to return based on video metadata
  return [
    { presetName: '2160p', ffmpegCmdStr: presets['2160p'].join(' ') },
    { presetName: '1440p', ffmpegCmdStr: presets['1440p'].join(' ') },
    { presetName: '1080p', ffmpegCmdStr: presets['1080p'].join(' ') },
    { presetName: '720p', ffmpegCmdStr: presets['720p'].join(' ') },
  ]; // placeholder
};
