services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: >
      --requirepass redis
  postgres:
    image: postgres:14-alpine
    ports:
      - 6001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tidal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: awstest
      AWS_SECRET_ACCESS_KEY: awstest
    volumes:
      - ./scripts/localstack:/docker-entrypoint-initaws.d
      - localstack:/tmp/localstack
volumes:
  pgdata:
  localstack:
