services:
  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    command: >
      --requirepass ${REDIS_PASSWORD}
  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tidal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  localstack:
    image: localstack/localstack:latest
    ports:
      - '${LOCALSTACK_PORT}:4566'
    environment:
      PERSISTENCE: 1
      EXTRA_CORS_EXPOSE_HEADERS: "*"
      EXTRA_CORS_ALLOWED_HEADERS: "*"
      EXTRA_CORS_ALLOWED_ORIGINS: "*"
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./scripts/localstack:/docker-entrypoint-initaws.d
      - localstack:/tmp/localstack
volumes:
  pgdata:
  localstack:
