services:
  tidal:
    build:
      dockerfile: Dockerfile
    entrypoint: [ "yarn", "start:dev" ]
    env_file:
      - .env.production
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/local/app/src
      # - /mnt/shack/media/gaming/tidal_dev:/tidal
      - /mnt/r2/rustyguts-transcoding:/tidal"
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
