services:
  redis: 
    image: redis:7-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    volumes: 
      - ./volumes/redis:/data
  postgres:
    restart: always
    image: postgres:15-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  localstack:
    restart: always
    image: localstack/localstack:latest
    ports:
      - ${LOCALSTACK_PORT}:4566
    environment:
      PERSISTENCE: 1
      DISABLE_CORS_CHECKS: 1
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./scripts/localstack:/docker-entrypoint-initaws.d
      - ./volumes/localstack:/tmp/localstack
  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
     - .env
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
  client:
    depends_on:
     - redis
     - server
     - postgres
     - localstack
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.dev_client
    ports:
      - ${REACT_PORT}:3000
    env_file:
      - .env
    volumes:
      - ./client/src:/usr/local/app/src
  server:
    depends_on:
     - redis
     - postgres
     - localstack
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.dev_server
    ports:
      - ${API_PORT}:3001
    env_file:
      - .env
    volumes:
      - ./server/src:/usr/local/app/src
      - ./server/views:/usr/local/app/views
      - ./server/prisma:/usr/local/app/prisma