FROM node:18-buster

# RUN wget https://github.com/shaka-project/shaka-packager/releases/download/v2.6.1/packager-linux-x64
# RUN mv ./packager-linux-x64 /usr/local/bin/packager
# RUN chmod +x /usr/local/bin/packager

ENV FFMPEG_VERSION="ffmpeg-n5.1-latest-linux64-gpl-5.1"
RUN wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${FFMPEG_VERSION}.tar.xz
RUN tar -xvf ${FFMPEG_VERSION}.tar.xz
RUN mv ${FFMPEG_VERSION}/bin/* /usr/bin/
RUN rm -rf ${FFMPEG_VERSION}*

WORKDIR /usr/local/app
COPY ./server/package.json .
COPY ./server/nodemon.json .
COPY ./server/tsconfig.json .

RUN yarn install --frozen-lockfile --development

EXPOSE 3001

CMD ["yarn", "dev"]