FROM node:18-alpine

WORKDIR /usr/local/app

COPY ./client/package.json .
COPY ./client/tsconfig.json .
COPY ./client/public ./public

RUN yarn install --frozen-lockfile --development

EXPOSE 3000

CMD ["yarn", "start"]