services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: >
      --requirepass redis
  database:
    container_name: postgres
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tidal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
volumes:
  pgdata:
  minio:
