services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: >
      --requirepass test
  database:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tidal
volumes:
  pgdata:
