#!/bin/bash

export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

export BUCKET_NAME="tidal"
export ENDPOINT="--endpoint-url=http://localhost:4566"

# AWS S3
aws $ENDPOINT s3 mb s3://$BUCKET_NAME