name: Deploy
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: chrislennon/action-aws-cli@v1.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.WASABI_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.WASABI_SECRET_ACCESS_KEY  }}
    - name: Deploy
      env:
        GZIP: -9
        GOOS: linux
        GOARCH: amd64
      run: |
        go build -o tidal main.go
        tar -czvf build.tar.gz ./tidal
        aws s3 cp ./build.tar.gz s3://cdn.bken.io/releases/tidal/latest.tar.gz --endpoint=https://s3.us-east-2.wasabisys.com
        aws s3 cp ./build.tar.gz s3://cdn.bken.io/releases/tidal/${{ github.sha }}.tar.gz --endpoint=https://s3.us-east-2.wasabisys.com
        rm -rf build.tar.gz tidal