name: Deploy Dev
env:
  ECS_SERVICE_NAME: web-dev
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v1
        with:
          name: target
          path: target
  ecr_docker_push:
    name: ECR Docker Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: target
      - uses: kciter/aws-ecr-action@v1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: tidal
          region: us-east-1
          tags: dev,${{ github.sha }}
          create_repo: false
  github_docker_push:
    name: Github Docker Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: target
      - name: Publish to GitHub
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          GIT_SHA: ${{ github.sha }}
        with:
          name: bken-io/tidal/tidal
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: GIT_SHA
  deploy:
    name: Deploy
    needs: ecr_docker_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: init
          tf_actions_working_dir: stack/dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: apply
          tf_actions_working_dir: stack/dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
