name: Deploy Docker
on:
  push:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to GitHub
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          GITHUB_REF: ${{ secrets.GITHUB_REF }}
        with:
          name: bken-io/tidal/tidal
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
          buildargs: GITHUB_REF
