name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bken-io/tidal/tidal
          username: ${{ github.actor }}
          registry: docker.pkg.github.com
          password: ${{ secrets.GITHUB_TOKEN }}
