name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: bken-io/tidal
          # token: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          registry: docker.pkg.github.com
