name: Master
on:
  push:
    branches:
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Tests
      run: go test -v ./...

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Build container image
        run: docker build 
          -t registry.digitalocean.com/bken/tidal:latest
          -t registry.digitalocean.com/bken/tidal:$GITHUB_SHA .

      - name: Login to DigitalOcean Docker Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/bken/tidal --all-tags