name: Deploy Prod
env:
  AWS_DEFAULT_REGION: us-east-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26
      - uses: borales/actions-yarn@v2.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install deps
        run: find . -name package.json -execdir yarn install --production {} \;

      - name: Terraform fmt
        id: fmt
        run: cd stack/prod && terraform fmt
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: cd stack/prod && terraform init
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        run: cd stack/prod && terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: cd stack/prod && terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: cd stack/prod && terraform apply -auto-approve -no-color
        continue-on-error: false
