name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      DOCKER_REGISTRY_URI: ${{ secrets.DOCKER_REGISTRY_URI }}
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Registry
        run: echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY_URI

      - name: Build container image
        run: docker build
          -t $DOCKER_REGISTRY_URI/tidal:latest
          -t $DOCKER_REGISTRY_URI/tidal:$GITHUB_SHA
          -f docker/Dockerfile .

      - name: Push image to Registry
        run: docker push $REGISTRY --all-tags
